# Use root/example as user/password credentials
version: '3.1'

services:
    postgres:
      image: postgres:9.6
      env_file: .env
      #environment:
      #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-todopwd}
      #  POSTGRES_USER: ${POSTGRES_USER:-todouser}
      #  POSTGRES_DB: ${POSTGRES_DB:-todo}
        #"POSTGRES_PASSWORD=password",
        #"POSTGRES_USER=user",
        #"POSTGRES_DB=db",
      restart: always
      #volumes:
      #  - postgres_data:"C:\Users\bear_\Desktop\Development\Projects\Docker\Postgres\Volumes"
      ports:  
        - "5432:5432"
  
    pgadmin:
      image: dpage/pgadmin4
      links:
        - postgres
      depends_on:
        - postgres
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: pwdpwd
      #volumes:
      #  - pgadmin:/root/.pgadmin
      ports:
        - "5050:80"
      
      #volumes:
      #  postgres_data:
        